function [a,time,b,x,c,y,d,z,e,yaw,f,x_sp,g,y_sp,h,z_sp,i1,yaw_sp] = importfile2(filename, startRow, endRow)
%IMPORTFILE2 Import numeric data from a text file as column vectors.
%   [A,TIME,B,X,C,Y,D,Z,E,YAW,F,X_SP,G,Y_SP,H,Z_SP,I1,YAW_SP] =
%   IMPORTFILE2(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [A,TIME,B,X,C,Y,D,Z,E,YAW,F,X_SP,G,Y_SP,H,Z_SP,I1,YAW_SP] =
%   IMPORTFILE2(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [a,time,b,x,c,y,d,z,e,yaw,f,x_sp,g,y_sp,h,z_sp,i1,yaw_sp] = importfile2('CircleVF_1_20s.txt',1, 2965);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/03/20 13:44:54

%% Initialize variables.
delimiter = {',',':'};
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,4,6,8,10,12,14,16,18]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [2,4,6,8,10,12,14,16,18]);
rawStringColumns = string(raw(:, [1,3,5,7,9,11,13,15,17]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [1,2,3,4,5,6,7,8,9]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Allocate imported array to column variable names
a = categorical(rawStringColumns(:, 1));
time = cell2mat(rawNumericColumns(:, 1));
b = categorical(rawStringColumns(:, 2));
x = cell2mat(rawNumericColumns(:, 2));
c = categorical(rawStringColumns(:, 3));
y = cell2mat(rawNumericColumns(:, 3));
d = categorical(rawStringColumns(:, 4));
z = cell2mat(rawNumericColumns(:, 4));
e = categorical(rawStringColumns(:, 5));
yaw = cell2mat(rawNumericColumns(:, 5));
f = categorical(rawStringColumns(:, 6));
x_sp = cell2mat(rawNumericColumns(:, 6));
g = categorical(rawStringColumns(:, 7));
y_sp = cell2mat(rawNumericColumns(:, 7));
h = categorical(rawStringColumns(:, 8));
z_sp = cell2mat(rawNumericColumns(:, 8));
i1 = categorical(rawStringColumns(:, 9));
yaw_sp = cell2mat(rawNumericColumns(:, 9));

clear a b c d e f g h il

